name: Generate Postman Docs

on: 
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Download Postman Collection from External Repository
        run: curl -o Club.postman_collection.json -fSL https://raw.githubusercontent.com/AlejoGomezC/cURL-test/main/collections/Club.postman_collection.json
        
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Run Newman and Generate Docs
        run: |
          chmod +x generate_docs.sh
          ./generate_docs.sh

      - name: Commit and Push Generated Docs
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docs/
          git commit -m 'Generated API documentation from Club Postman collection' || echo "No changes to commit"
          git push
