# This workflow will build and deploy a .NET project locally and document the responses
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: postman-collection
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'AlejoGomezC/HPlusSport-API-.NET'

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run API locally
      run: dotnet run --project ./HPlusSport.API &
      
    - name: Install Newman
      run: npm install -g newman

    - name: Download Postman collection
      run: curl -o MyFirst.NetApi.postman_collection.json -fSL https://raw.githubusercontent.com/AlejoGomezC/cURL-test/main/collections/MyFirst.NetApi.postman_collection.json
    
    - name: Run Postman collection
      run: newman run MyFirst.NetApi.postman_collection.json

    - name: Document API responses
      run: |
        mkdir -p docs
        touch docs/.Net_README.md
        jq -r '.item[] | "- **" + .name + "**\n  - Method: " + .request.method + "\n  - URL: " + .request.url.raw + "\n  - Body: ```json\n" + (.request.body.raw // "No body") + "\n```\n  - Response: ```json\n" + (.response[0].body // "No response") + "\n```\n"' MyFirst.NetApi.postman_collection.json >> docs/.Net_README.md
        echo "Parsed JSON and updated .NET README.md"

    - name: Commit and Push Generated Docs
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'Generated API documentation from .NET Postman collection' || echo "No changes to commit"
        git push



      
